import raw from './teams.json';

export type Team = {
	abbr: string;
	name: string;
	nickname: string;
	conference: 'AFC' | 'NFC';
	division: string;
	primaryColor: string;
	secondaryColor: string;
	logo: string;
};

/** Generated by `pipeline/football_pipeline/teams.py`, already in canonical division order. */
export const teams = raw as Team[];

export const teamsByAbbr = new Map(teams.map((t) => [t.abbr, t]));

export const DIVISIONS = [
	'AFC North',
	'AFC East',
	'AFC South',
	'AFC West',
	'NFC North',
	'NFC East',
	'NFC South',
	'NFC West'
] as const;

export const teamsByDivision = DIVISIONS.map((division) => ({
	division,
	teams: teams.filter((t) => t.division === division)
}));
